-- 풋살 전용 테이블 (futsal_events, futsal_event_participation, futsal_event_comments)
-- 기존 DB에 테이블이 없을 때만 생성하도록 IF NOT EXISTS 사용

-- 1. 풋살 이벤트 테이블
CREATE TABLE IF NOT EXISTS futsal_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date DATE NOT NULL,
  time TEXT,
  location TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'completed', 'cancelled')),
  created_by UUID REFERENCES players(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 2. 풋살 이벤트 참가/불참 테이블 (유저별 이벤트당 1행)
CREATE TABLE IF NOT EXISTS futsal_event_participation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES futsal_events(id) ON DELETE CASCADE,
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('attending', 'not_attending', 'pending')),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE(event_id, player_id)
);

-- 3. 풋살 이벤트 댓글 테이블
CREATE TABLE IF NOT EXISTS futsal_event_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES futsal_events(id) ON DELETE CASCADE,
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 인덱스 (조회 성능)
CREATE INDEX IF NOT EXISTS idx_futsal_event_participation_event_id ON futsal_event_participation(event_id);
CREATE INDEX IF NOT EXISTS idx_futsal_event_participation_player_id ON futsal_event_participation(player_id);
CREATE INDEX IF NOT EXISTS idx_futsal_event_comments_event_id ON futsal_event_comments(event_id);
CREATE INDEX IF NOT EXISTS idx_futsal_events_date ON futsal_events(date);
CREATE INDEX IF NOT EXISTS idx_futsal_events_created_by ON futsal_events(created_by);
