-- 축구/풋살별 접근 권한 테이블 (회원별 스포츠 접근 여부)
-- 기존 회원은 마이그레이션으로 축구 권한 부여

CREATE TABLE IF NOT EXISTS player_sport_access (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  sport TEXT NOT NULL CHECK (sport IN ('soccer', 'futsal')),
  can_access BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE(player_id, sport)
);

CREATE INDEX IF NOT EXISTS idx_player_sport_access_player_id ON player_sport_access(player_id);
CREATE INDEX IF NOT EXISTS idx_player_sport_access_sport ON player_sport_access(sport);

-- 기존 players 전원에게 축구 권한 부여 (이미 있으면 무시)
INSERT INTO player_sport_access (player_id, sport, can_access)
SELECT id, 'soccer', true FROM players
ON CONFLICT (player_id, sport) DO NOTHING;
