-- 1. players 테이블에 futsal-manager 역할 추가
-- (PostgreSQL: 기존 CHECK 제약 제거 후 새 값 포함해 재생성)
DO $$
BEGIN
  ALTER TABLE players DROP CONSTRAINT IF EXISTS players_role_check;
  ALTER TABLE players ADD CONSTRAINT players_role_check
    CHECK (role IN ('player', 'president', 'vice_president', 'coach', 'assistant_coach', 'treasurer', 'system-manager', 'futsal-manager'));
EXCEPTION
  WHEN undefined_object THEN
    ALTER TABLE players ADD CONSTRAINT players_role_check
      CHECK (role IN ('player', 'president', 'vice_president', 'coach', 'assistant_coach', 'treasurer', 'system-manager', 'futsal-manager'));
END $$;

-- 2. 풋살 접근 권한 요청 테이블
CREATE TABLE IF NOT EXISTS futsal_access_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  message TEXT,
  requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMP WITH TIME ZONE,
  reviewed_by UUID REFERENCES players(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_futsal_access_requests_player_id ON futsal_access_requests(player_id);
CREATE INDEX IF NOT EXISTS idx_futsal_access_requests_status ON futsal_access_requests(status);
CREATE INDEX IF NOT EXISTS idx_futsal_access_requests_requested_at ON futsal_access_requests(requested_at);

-- 동일 회원이 pending 요청을 중복으로 넣지 않도록 (선택)
CREATE UNIQUE INDEX IF NOT EXISTS idx_futsal_access_requests_one_pending_per_player
  ON futsal_access_requests(player_id) WHERE status = 'pending';
