-- 구 구조(player_id, sport, can_access)일 때만 실행.
-- player_sport_access에 sport, can_access 컬럼이 있을 때 사용.

-- 1. 새 구조 테이블 생성 (회원 이름 포함)
CREATE TABLE IF NOT EXISTS player_sport_access_new (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  name TEXT,
  soccer_access BOOLEAN NOT NULL DEFAULT true,
  futsal_access BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE(player_id)
);

CREATE INDEX IF NOT EXISTS idx_player_sport_access_new_player_id ON player_sport_access_new(player_id);

-- 2. 기존 데이터 이전 (players + 구 player_sport_access)
INSERT INTO player_sport_access_new (player_id, name, soccer_access, futsal_access)
SELECT
  p.id,
  p.name,
  COALESCE(s.soccer, true),
  COALESCE(f.futsal, false)
FROM players p
LEFT JOIN (SELECT player_id, can_access AS soccer FROM player_sport_access WHERE sport = 'soccer') s ON p.id = s.player_id
LEFT JOIN (SELECT player_id, can_access AS futsal FROM player_sport_access WHERE sport = 'futsal') f ON p.id = f.player_id
ON CONFLICT (player_id) DO UPDATE SET
  name = EXCLUDED.name,
  soccer_access = EXCLUDED.soccer_access,
  futsal_access = EXCLUDED.futsal_access,
  updated_at = NOW();

-- 3. 구 테이블 삭제 후 새 테이블 이름 변경
DROP TABLE IF EXISTS player_sport_access;
ALTER TABLE player_sport_access_new RENAME TO player_sport_access;
ALTER INDEX IF EXISTS idx_player_sport_access_new_player_id RENAME TO idx_player_sport_access_player_id;
