-- 축구 접근 권한 요청 테이블 (풋살 권한 요청과 동일 구조)
CREATE TABLE IF NOT EXISTS soccer_access_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  message TEXT,
  requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMP WITH TIME ZONE,
  reviewed_by UUID REFERENCES players(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_soccer_access_requests_player_id ON soccer_access_requests(player_id);
CREATE INDEX IF NOT EXISTS idx_soccer_access_requests_status ON soccer_access_requests(status);
CREATE INDEX IF NOT EXISTS idx_soccer_access_requests_requested_at ON soccer_access_requests(requested_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_soccer_access_requests_one_pending_per_player
  ON soccer_access_requests(player_id) WHERE status = 'pending';
