-- Running 테이블 생성
-- 런닝 기록을 저장하는 테이블

CREATE TABLE running_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id UUID REFERENCES players(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  distance DECIMAL(5, 2) NOT NULL, -- 거리 (km, 소수점 2자리까지)
  duration INTEGER NOT NULL, -- 시간 (분 단위)
  pace DECIMAL(5, 2), -- 평균 페이스 (분/km, 계산 가능)
  notes TEXT, -- 메모/노트
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 인덱스 생성
CREATE INDEX idx_running_records_player_id ON running_records(player_id);
CREATE INDEX idx_running_records_date ON running_records(date);
CREATE INDEX idx_running_records_player_date ON running_records(player_id, date);

-- 코멘트 추가
COMMENT ON TABLE running_records IS '선수들의 런닝 기록을 저장하는 테이블';
COMMENT ON COLUMN running_records.distance IS '런닝 거리 (km)';
COMMENT ON COLUMN running_records.duration IS '런닝 시간 (분)';
COMMENT ON COLUMN running_records.pace IS '평균 페이스 (분/km) - distance와 duration으로 계산 가능';
