-- 작전판 관련 마이그레이션 스크립트
-- 기존 데이터베이스를 유지하면서 작전판 기능만 추가

-- 1. Tactics 테이블 생성 (기존 matches 테이블과 연결)
CREATE TABLE IF NOT EXISTS tactics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE,
  match_number INTEGER DEFAULT 1, -- 같은 경기 내에서 몇 번째 경기인지 (1, 2, 3...)
  name TEXT NOT NULL DEFAULT '작전판',
  team_a_strategy TEXT,
  team_b_strategy TEXT,
  created_by UUID REFERENCES players(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(match_id, match_number)
);

-- 2. Match_Attendance에 작전판 관련 컬럼 추가 (이미 있으면 무시)
DO $$ 
BEGIN
    -- match_number 컬럼 추가 (경기별 구분용)
    BEGIN
        ALTER TABLE match_attendance ADD COLUMN match_number INTEGER DEFAULT 1;
    EXCEPTION
        WHEN duplicate_column THEN
            RAISE NOTICE 'match_number 컬럼이 이미 존재합니다.';
    END;
    
    -- tactics_position_x 컬럼 추가
    BEGIN
        ALTER TABLE match_attendance ADD COLUMN tactics_position_x DECIMAL(5,2);
    EXCEPTION
        WHEN duplicate_column THEN
            RAISE NOTICE 'tactics_position_x 컬럼이 이미 존재합니다.';
    END;
    
    -- tactics_position_y 컬럼 추가
    BEGIN
        ALTER TABLE match_attendance ADD COLUMN tactics_position_y DECIMAL(5,2);
    EXCEPTION
        WHEN duplicate_column THEN
            RAISE NOTICE 'tactics_position_y 컬럼이 이미 존재합니다.';
    END;
    
    -- tactics_team 컬럼 추가
    BEGIN
        ALTER TABLE match_attendance ADD COLUMN tactics_team TEXT CHECK (tactics_team IN ('A', 'B'));
    EXCEPTION
        WHEN duplicate_column THEN
            RAISE NOTICE 'tactics_team 컬럼이 이미 존재합니다.';
    END;
    
    -- substitutions 컬럼 추가
    BEGIN
        ALTER TABLE match_attendance ADD COLUMN substitutions INTEGER DEFAULT 0;
    EXCEPTION
        WHEN duplicate_column THEN
            RAISE NOTICE 'substitutions 컬럼이 이미 존재합니다.';
    END;
    
    -- is_substituted 컬럼 추가
    BEGIN
        ALTER TABLE match_attendance ADD COLUMN is_substituted BOOLEAN DEFAULT FALSE;
    EXCEPTION
        WHEN duplicate_column THEN
            RAISE NOTICE 'is_substituted 컬럼이 이미 존재합니다.';
    END;
END $$;

-- 3. 인덱스 생성 (이미 있으면 무시)
DO $$ 
BEGIN
    BEGIN
        CREATE INDEX idx_tactics_match_id_number ON tactics(match_id, match_number);
    EXCEPTION
        WHEN duplicate_object THEN
            RAISE NOTICE 'idx_tactics_match_id_number 인덱스가 이미 존재합니다.';
    END;
    
    BEGIN
        CREATE INDEX idx_match_attendance_tactics ON match_attendance(match_id, match_number, player_id);
    EXCEPTION
        WHEN duplicate_object THEN
            RAISE NOTICE 'idx_match_attendance_tactics 인덱스가 이미 존재합니다.';
    END;
END $$;

-- 4. 경기 삭제 시 tactics 테이블 자동 삭제를 위한 트리거 함수
CREATE OR REPLACE FUNCTION delete_tactics_on_match_delete()
RETURNS TRIGGER AS $$
BEGIN
    -- 경기가 삭제되면 해당 경기의 모든 작전판도 삭제
    DELETE FROM tactics WHERE match_id = OLD.id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- 5. 트리거 생성 (이미 있으면 무시)
DO $$ 
BEGIN
    BEGIN
        CREATE TRIGGER trigger_delete_tactics_on_match_delete
        AFTER DELETE ON matches
        FOR EACH ROW
        EXECUTE FUNCTION delete_tactics_on_match_delete();
    EXCEPTION
        WHEN duplicate_object THEN
            RAISE NOTICE 'trigger_delete_tactics_on_match_delete 트리거가 이미 존재합니다.';
    END;
END $$;

-- 6. 샘플 데이터 추가 (기존 데이터가 없는 경우에만)

-- 샘플 작전판 추가 (첫 번째 경기의 1경기에 대해)
INSERT INTO tactics (match_id, match_number, name, team_a_strategy, team_b_strategy, created_by)
SELECT 
    1 as match_id,
    1 as match_number,
    'FC 서울전 1경기 작전판' as name,
    'A팀: 압박 축구로 상대를 압도하자' as team_a_strategy,
    'B팀: 안정적인 수비로 역습 기회를 노리자' as team_b_strategy,
    (SELECT id FROM players WHERE role = 'president' LIMIT 1) as created_by
WHERE NOT EXISTS (
    SELECT 1 FROM tactics t 
    WHERE t.match_id = 1 AND t.match_number = 1
);

-- 샘플 작전판 선수 배치 정보 추가 (첫 번째 경기의 1경기 참석 선수들에 대해)
UPDATE match_attendance SET 
    match_number = 1,
    tactics_position_x = 25.0, 
    tactics_position_y = 50.0, 
    tactics_team = 'A'
WHERE match_id = 1 
AND player_id = (SELECT id FROM players WHERE role = 'player' LIMIT 1);

UPDATE match_attendance SET 
    match_number = 1,
    tactics_position_x = 35.0, 
    tactics_position_y = 30.0, 
    tactics_team = 'A'
WHERE match_id = 1 
AND player_id = (SELECT id FROM players WHERE role = 'player' LIMIT 1 OFFSET 1);

UPDATE match_attendance SET 
    match_number = 1,
    tactics_position_x = 15.0, 
    tactics_position_y = 50.0, 
    tactics_team = 'A'
WHERE match_id = 1 
AND player_id = (SELECT id FROM players WHERE role = 'player' LIMIT 1 OFFSET 2);

-- 완료 메시지
SELECT '작전판 마이그레이션이 완료되었습니다.' as message;
